### ISSUE TITLE
Initial ComboBox.setValue doesn't work

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-combo-box-flow#37] opened 2018-01-08 06:15 UTC
@henrikerola commented on [Sun Jan 07 2018](https://github.com/vaadin/flow/issues/3274)

The following code doesn't set "Item 2" as a selected item:

```
ComboBox<String> comboBox = new ComboBox<>();
comboBox.setItems("Item 1", "Item 2");
comboBox.setValue("Item 2");
add(comboBox);
```
However, clicking on this button on the same page would select "Item 2":

```
Button button = new Button("Set value");
button.addClickListener(e -> {
  comboBox.setValue("Item 2");
});
add(button);
```

Tested with 10.0.0.alpha11.

---

@ZheSun88 commented on [Mon Jan 08 2018](https://github.com/vaadin/flow/issues/3274#issuecomment-355890344)

thought this is quite related to the component itself, so i will move this issue to its own repository. :-)

**Comment by ZheSun88** [comment] 2018-01-10 08:09
is this related with https://github.com/vaadin/flow/issues/2930 ? 

in the PR https://github.com/vaadin/vaadin-combo-box-flow/pull/38 , `setValue()` has been reimplemented.  might make some differences.

**Comment by pleku** [comment] 2018-01-11 09:48
Might also be a duplicate of https://github.com/vaadin/flow/issues/2930, need to verify this after both that and #38 are fixed.

**Comment by denis-anisimov** [comment] 2018-01-13 09:33
I cannot reproduce this.
Neither of two code snippets below reproduces the issue:

ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("a", "b");

        comboBox.setValue("b");
        NativeButton button = new NativeButton("Show Combo",
                event -> add(comboBox));
        add(button);
ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("a", "b");

        comboBox.setValue("b");
        add(comboBox);
In both cases I see "b" as a selected item in the combo-box.

**Closed** 2018-01-15 09:53 UTC
Labels: bug, components, investigation
