### ISSUE TITLE
Connector problems with 2.1.2 - Cannot read property 'enableClientValidation' of undefined

### ISSUE THREAD

**Issue by lucastanzani** [vaadin/vaadin-combo-box-flow#235] opened 2019-03-19 12:28 UTC
I must say this may be a derivation - duplication of https://github.com/vaadin/vaadin-combo-box-flow/issues/219
My setup is vaadin 13.0.1 and combobox explicitly set to version 2.1.2 through pom dependency.
I have a form with a combobox with a binder. The underlying bound object has a @Id and  asRequired is set for the property the combobox must hold. 
Example: 

```
binder.forField(studentBox)
                .asRequired("Inserire uno studente a cui associare la partecipazione!")
                .withConverter(
                        studentService::idToStudent, studentService::studentToId,
                        "Inserire uno studente tra quelli dell'elenco")
                .bind(Participation::getStudent, Participation::setStudent);
```
The combobox displays the id of the student to add to the Participation, which is the entity.
When i call readBean(some_participation) i get this error:
client-28831013082792340517B7074033EF04.cache.js:975 Exception is thrown during JavaScript execution. Stacktrace will be dumped separately.
The error has occurred in the JS code: '$0, $1, $0.$connector.enableClientValidation($1)'

```
Uncaught TypeError: Cannot read property 'enableClientValidation' of undefined
    at Object.eval (eval at jt (client-28831013082792340517B7074033EF04.cache.js:975), <anonymous>:3:15)
    at jt (client-28831013082792340517B7074033EF04.cache.js:975)
    at it (client-28831013082792340517B7074033EF04.cache.js:931)
    at gt (client-28831013082792340517B7074033EF04.cache.js:562)
    at Pq (client-28831013082792340517B7074033EF04.cache.js:482)
    at lr.mr [as W] (client-28831013082792340517B7074033EF04.cache.js:983)
    at eA (client-28831013082792340517B7074033EF04.cache.js:866)
    at sk (client-28831013082792340517B7074033EF04.cache.js:731)
    at Dk.Ek [as W] (client-28831013082792340517B7074033EF04.cache.js:983)
    at eA (client-28831013082792340517B7074033EF04.cache.js:866)
    at Rq (client-28831013082792340517B7074033EF04.cache.js:978)
    at fr.gr [as D] (client-28831013082792340517B7074033EF04.cache.js:983)
    at zj (client-28831013082792340517B7074033EF04.cache.js:749)
    at Ej.Gj [as V] (client-28831013082792340517B7074033EF04.cache.js:983)
    at fm (client-28831013082792340517B7074033EF04.cache.js:833)
    at Cm.Em [as V] (client-28831013082792340517B7074033EF04.cache.js:983)
    at HTMLLinkElement.<anonymous> (client-28831013082792340517B7074033EF04.cache.js:934)
    at sb (client-28831013082792340517B7074033EF04.cache.js:413)
    at vb (client-28831013082792340517B7074033EF04.cache.js:850)
    at HTMLLinkElement.<anonymous> (client-28831013082792340517B7074033EF04.cache.js:592)
```
The combobox is empty as readBean is called.
This error only happens the first time i try this.
This error has been there from 12.0.6 on, until now. With 12.0.5 everything works fine.

**Comment by pekam** [comment] 2019-03-19 12:46
This kind of issues are often caused by the browser caching the old version of a script file.
Try doing a force refresh on the browser, or disable the cache.

**Comment by lucastanzani** [comment] 2019-03-19 12:53
@pekam I tried it with both cache disabled (through the consolle), and force refresh, and even deleting the cache and trying with other browsers. It still unfortunately happens.

**Comment by watho** [comment] 2019-05-06 10:59
Are there any news on this? 13.0.5 gives me still this error. So i'm stuck at 12.0.5, which is deprecated because of the new fast release cycle.

**Comment by pekam** [comment] 2019-05-06 12:37
Can you verify, does this issue occur only if data is given to combo box after setting the binding? So is this a duplicate of [this ticket](https://github.com/vaadin/flow/issues/5082)?
Also, is there a use case where you don't want to provide data to the combo box immediately?

**Comment by watho** [comment] 2019-05-06 14:15
The error occured in a rather large application. I will try to narrow it down to a smaller example.

My usecase is a crud-form alongside a grid with selectable items. The entries of the combobox depends on the selected item. So the box is empty when no item is selected and will be newly filled on every selection change in the grid.

**Comment by pekam** [comment] 2019-05-07 07:31
I'd guess that setting an empty item-set should fix the issue in your case. So instead of not setting items at all, call `comboBox.setItems()`.

Currently the combo box doesn't really work without giving either items or a data provider. It will throw an exception when opening the combo box. I was thinking that maybe combo box could set the empty item set by default, when no items or data provider are defined. The only possible downside with this is that `getDataProvider()` would return a `ListDataProvider` backed by an empty list, even when the user has not set anything. But this is maybe not a real problem.

**Comment by pekam** [comment] 2019-05-07 08:18
I've created a PR which should at least fix the particular client-side error `Uncaught TypeError: Cannot read property 'enableClientValidation' of undefined` #252 

I'm working on another fix so the combo box wouldn't throw when opened when no items or data provider are set #253

**Closed** 2019-05-07 09:50 UTC
Labels: bug, components

**Comment by watho** [comment] 2019-05-07 15:30
Thank you very much for your efforts. Setting an empty dataprovider before the binding works for me.

**Comment by pekam** [comment] 2019-05-08 06:15
Good to hear. :) That workaround should become unnecessary once the fixes are released (at latest in Vaadin 14).

**Comment by Braus** [comment] 2019-10-04 13:52
Also found this bug

**Comment by pekam** [comment] 2019-10-04 13:56
@Braus, which Vaadin version are you using?

**Comment by Braus** [comment] 2019-10-04 14:00
13.0.11 I think or something like that. not Vaadin 14 in any case..

**Comment by pekam** [comment] 2019-10-04 14:02
Vaadin 13 is not supported anymore, so you should update to 14, which has long-term support.

It might be that the fix for this issue never got backported to V13.
