### ISSUE TITLE
entering value in dialog which is not contained in items breaks combo box

### ISSUE THREAD

**Issue by bbaumgartner** [vaadin/vaadin-combo-box-flow#196] opened 2019-01-29 15:41 UTC
Hello, I have a problem with combo boxes in dialogs in vaadin 12.0.4

        public final class AddDeliveryWizard extends Dialog {
        
        
            public AddDeliveryWizard() {
                super(createContent());
            }
        
            protected static Component createContent() {
                ComboBox<Object> combobox = new ComboBox<>();
        
                combobox.setItems("One", "Two", "Three", "Four");
                combobox.setItemLabelGenerator(Object::toString);
                combobox.addValueChangeListener(event -> System.out.println("Value changed from " + event.getOldValue() + " to " + event.getValue() + " and the combobox value is " + combobox.getValue()));
        
                return new VerticalLayout(new TextField(), combobox);
            }
        
        
        }

1. Open the dialog
2. Enter 1 into text field
3. press tab
4. Enter 1 into combo box
5. Try to select any value from the combo box
IS: The value change listener is no longer triggered

![dialog](https://user-images.githubusercontent.com/6337810/51920940-af2e2d00-23e6-11e9-84af-7614c7e353c1.gif)

It looks like as soon as you enter 1 into the combo box, com.vaadin.flow.data.provider.DataCommunicator#doUnregister is called and removes all elements from the keyMapper. After that the combo box is broken, although the UI shows the correct selected value the server side is no longer notified about the selected value.

Best Regards
Benno

**Comment by pekam** [comment] 2019-05-15 13:13
Hi!

I couldn't reproduce this bug with Vaadin 13.0.7, so I'm closing the issue.

If I'm missing something and you think the issue is still relevant, feel free to reopen it and provide more info.

**Closed by pekam** 2019-05-15 13:13 UTC
Labels: bug
