### ISSUE TITLE
Increasing page size breaks filtering

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-combo-box-flow#201] opened 2019-02-05 07:51 UTC
`<vaadin.version>12.0.5</vaadin.version>`
Use case: need to show a somewhat large amount of items in a ComboBox with client-side filtering. The JavaDocs in setDataProvider say:

> To force client-side filtering with a larger
> data set (at the cost of increased network traffic), you can increase the
> page size with `{@link #setPageSize(int)}.`

However, using this seems to break the filtering entirely. Code sample:
```
        ListDataProvider<String> ldp = new ListDataProvider<>(IntStream.range(0, 100).
                mapToObj(number -> "Item: " + number).
                collect(Collectors.toList()));
        ComboBox<String> myComboBox = new ComboBox<>("Combo");
        /* increase page size to be greater than the amount of items so filtering
         * should happen on the client side
         */
        myComboBox.setPageSize(101);
        myComboBox.setDataProvider(ldp);
```
When running this, typing anything in the input field just flashes the dropdown and shows nothing.
https://www.youtube.com/watch?v=PTx6ERxGDd0&feature=youtu.be

**Comment by pekam** [comment] 2019-02-13 12:25
This is a bug in the web component which slipped into the platform because the Flow component was released with a different web component version than what was included into the platform.

Everything should work properly with the upcoming web component release 4.2.5

**Comment by pekam** [comment] 2019-02-14 08:33
This doesn't need an additional regression test because of the following reason:

- `vaadin-combo-box-flow` 2.0.2 was released with the webjar version 4.2.0
- Vaadin platform 12.0.5 was released with the Flow component 2.0.2, and webjar 4.2.2
- The bug occurs with webjar 4.2.2, but not with 4.2.0.
- If the versions would have been in sync, and the Flow component was released and tested with webjar 4.2.2, the existing integration tests would have caught this issue.

**Comment by OlliTietavainenVaadin** [comment] 2019-02-14 08:54
I understood about 30% of that, but cool

**Comment by pekam** [comment] 2019-02-14 09:54
I'm closing this with `abandoned` milestone, because technically it was never a bug in this repository. It is a platform bug because the platform depends on incompatible versions of the web component and the Flow component. The problem still exists in the platform until the versions are updated to the latest ones.

**Closed by pekam** 2019-02-14 09:54 UTC
