### ISSUE TITLE
Please make dropdown width configurable

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-combo-box-flow#387] opened 2020-08-28 07:20 UTC
In certain apps, certain ComboBoxes tend to have items with long texts. If the text won't fit the default dropdown popup width, the text will wrap, which is often not desired.

It would be good to have a means to override the dropdown width and specify an exact number in pixels.

Workaround can be found in the forums: https://vaadin.com/forum/thread/18082676/combobox-dropdown-list-width

**Comment by mvysny** [comment] 2020-08-28 07:37
There's even simpler workaround without any need to introduce custom CSS:

```kotlin
comboBox.element.style.set("--vaadin-combo-box-overlay-width", width.trim())
```

**Comment by web-padawan** [comment] 2020-09-07 06:37
Closing as duplicate of #155

**Closed by web-padawan** 2020-09-07 06:37 UTC
Labels: enhancement
