### ISSUE TITLE
(TypeError) : $0.$connector is undefined

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-combo-box-flow#181] opened 2018-12-31 15:52 UTC
https://vaadin.com/forum/thread/17446327/typeerror-0-connector-is-undefined

Happens in comboBox.setItems(Collection)

when called from beforeEnter(BeforeEnterEvent)

in a class with Signature

@UIScope public class OverviewView extends PolymerTemplate<OverviewView.OverviewViewModel> implements HasComponents, BeforeEnterObserver

    <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-combo-box-flow</artifactId>
        <version>1.1.0</version>
    </dependency>

This version of vaadin-combo-box-flow does not expose the problem for me.

Of course, it is not advised to simply downgrade this in Maven, but it does the trick for me; for the time being (no functionality hooked up yet though).

2.0.0 and 2.0.1 do have the problem.

**Comment by martinisraelsen** [comment] 2018-12-31 20:19
This happened for me with two ComboBoxes, the valueChangeListener for ComboBox1 calls setItems for ComboBox2. If ComboBox2 doesn't have any items (setItems was never called), I'd get the TypeError. Populating ComboBox2 with an empty list made the problem go away.

**Comment by Silver-Wulf** [comment] 2019-01-13 04:18
This seems related to #169 as the errors the client showed were fields of $connector. It seems if the DataProvider is not set to a non-null value prior to the page load then the $connector field is never initialized.

**Comment by ericmartinezr** [comment] 2019-01-24 12:50
Same happened to me.

This works with the solution suggested by @Silver-Wulf  (thanks by the way)

```java
		ComboBox<MyBean> cb = new ComboBox<>();
		// Initialize to an empty bean as a workaround 
		// https://github.com/vaadin/vaadin-combo-box-flow/issues/181
		cb.setItems(new MyBean());
		
		TextField txt = new TextField();
		txt.addValueChangeListener(event -> {
			List<MyBean> beans = respository.findAll(...);
			cb.setDataProvider(DataProvider.ofCollection(beans));
		});
		
```

This will fail with OP error

```java
		ComboBox<MyBean> cb = new ComboBox<>();
		// No initialization
		
		TextField txt = new TextField();
		txt.addValueChangeListener(event -> {
			List<MyBean> beans = respository.findAll(...);
			cb.setDataProvider(DataProvider.ofCollection(beans));
		});
```

**Comment by pekam** [comment] 2019-02-11 09:50
I think this is a duplicate of https://github.com/vaadin/vaadin-combo-box-flow/issues/169, which was fixed by @Silver-Wulf in https://github.com/vaadin/vaadin-combo-box-flow/pull/188, and tested in https://github.com/vaadin/vaadin-combo-box-flow/pull/190. 

@bogdanudrescu, you reviewed the fix and created the test, so can you verify if this is really fixed and possibly close the issue?

**Comment by pleku** [comment] 2019-03-21 11:22
This should have been fixed already, please comment here if not so.

**Closed by pleku** 2019-03-21 11:22 UTC
