### ISSUE TITLE
Add api setClearButtonVisible

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-combo-box-flow#228] opened 2019-03-07 13:36 UTC
Now that TextField has this API would be nice to have it available for ComboBox too.

**Comment by denis-anisimov** [comment] 2019-03-07 14:03
I would say this is duplicate of https://github.com/vaadin/vaadin-combo-box-flow/issues/79.
What do you think ?
At least semantically they are about the same. It doesn't have to be done via the `setRequired` method. May be another additional API is needed for that.

At least the mentioned issue contains a way how to do it as a workaround.

**Comment by Wnt** [comment] 2019-03-08 07:36
I think this would be much more easy to implement than #79, so I would not mark this as a duplicate.
For now I have used this workaround to hide the clear button:

`shared-styles.html`:

```
<dom-module id="combo-box-clear-button-visibility-extension" theme-for="vaadin-combo-box">
    <template>
        <style>
            :host(vaadin-combo-box) [part="clear-button"] {
                display: var(--display-clear-button, block);
            }
        </style>
    </template>
</dom-module>
```

and then I can use the style API on the server side to hide the clear button:
`combobox.getStyle().set("--display-clear-button", "none");`

**Comment by denis-anisimov** [comment] 2019-03-08 07:39
Well, we need some support from the client side anyway to support this properly. And that's a part of #79.
But let's keep this as a separate ticket.

**Comment by pekam** [comment] 2019-03-18 07:41
This depends on https://github.com/vaadin/vaadin-combo-box/issues/786

**Closed** 2019-04-29 12:47 UTC
Labels: awaits another ticket, enhancement, in review
