### ISSUE TITLE
14rc2, 14rc3. Combobox can't be added to a UI

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-combo-box-flow#280] opened 2019-07-03 08:25 UTC
There is no way to add a Combobox via Java Api. Broken in rc2, rc3

Code to reproduce: 
```
ComboBox<String> cb=new ComboBox<>();
add(cb);
```

Output: 
`Uncaught TypeError: Cannot read property 'confirm' of undefined at Object.eval`
`Uncaught TypeError: Cannot read property 'set' of undefined at Object.eval`
`Uncaught TypeError: Cannot read property 'updateSize' of undefined at Object.eval`

**Comment by pekam** [comment] 2019-07-03 09:46
I couldn't reproduce the issue with a fresh starter from vaadin.com/start (14.0.0.rc3).

**Comment by anasmi** [comment] 2019-07-03 10:11
Does it work for you in rc2? (I've updated from rc2, so it might affect things:/ )

**Comment by robert-lee-hisl** [comment] 2019-07-03 10:20
May or may not be related, but I've had the same Javascript errors with a Java-added combo box in 14 beta2, when refreshing (not navigating to) the page with the @PreserveOnRefresh annotation.

**Comment by pekam** [comment] 2019-07-03 10:34
Works for me in rc2 as well. Also, `PreserveOnRefresh` works for me (tested with rc3).

**Comment by anasmi** [comment] 2019-07-03 11:05
I can't reproduce anymore either :/

**Comment by pekam** [comment] 2019-07-03 11:19
The issue is most likely related to how Flow loads resources, but hard to tell exactly without being able to reproduce it. Anyway, there shouldn't be anything wrong with the component implementation, so I'm closing this issue.

**Closed by pekam** 2019-07-03 11:19 UTC

**Comment by TheSilentHorizon** [comment] 2019-08-05 15:57
Had the same issue too on RC7. Background Information on this:

I have a modified webpack.config.js which tries to expose jquery. Why so ever, (i created an ticket for this), Babel-Multi-Target Plugin fails. So i switched to the default babel-loader. This works. 

Now, i tried to add the very first combobox in my project, and i got the same exact error as OP.

Heres my webpack.config.js, maybe this helps reproducing the error....

```
flowDefaults.module.rules[0].use = ["babel-loader"]
module.exports = merge(flowDefaults, {
    resolve: {
        alias: {
            'jquery': require.resolve('jquery'),
        }
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            'window.$': 'jquery'
        })
    ],
    module: {
        rules: [{
            test: require.resolve('jquery'),
            use: [{
                loader: 'expose-loader',
                options: 'jQuery'
            }, {
                loader: 'expose-loader',
                options: '$'
            }
            ]
        },
            {
                test: /bootstrap-v4-rtl\/dist\/js\//,
                use: 'imports-loader?jQuery=jquery'
            }],
    },
});
```
