### ISSUE TITLE
ComboBox method `isInvalid` does not work

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-combo-box-flow#114] opened 2018-08-02 14:47 UTC
_ComboBox<String> cb = new ComboBox<>( );
...
if( cb.isInvalid( ) ) {
return;
}_
...
**//CODE NEVER COMES TO THIS LINE
//And Combobox never gets RED except I click and focus that component**

**Comment by denis-anisimov** [comment] 2018-08-06 08:13
Sorry, I don't understand this ticket.

When you create a ticket it should contain:
- Exact steps to reproduce.
- Current behavior
- Expected behavior

From the code in the description I understand that `cb` is always invalid.
This is not true. I've just checked that newly created combobox has `invalid`   value `false`.
So either the code snippet is incorrect or there is something in `...` which makes this behavior.
It means that this `...` should be written clearly in the bug description.

This comment `And Combobox never gets RED except I click and focus that component` is also cryptic for me.
Why should it get red? What action do you do to make it red.
By default ComboBox is valid. So it should not be marked red.

Normally `invalid`  property should be set explicitly to show that the component is invalid.
Usually it happens if a component is used by `Binder`   which is able to validate a component.
If you have set a validator for the component and validation fails then `invalid` flag is set from the server side.

So : what's your usecase ? Do you update `invalid` property manually or do you use a binder with validator?
Why a `ComboBox` should be made `invalid` ?

I'm closing this ticket since I don't see an issue here.
Please reopen with answers to all questions and exact scenario to reproduce if you still think there is a bug.

**Closed by denis-anisimov** 2018-08-06 08:13 UTC

**Comment by ugurdoksan** [comment] 2018-08-07 09:29
The comment I wrote was wrong. I corrected it as 'CODE ALWAYS COMES TO THIS LINE'.

In my scenario, I use a Verticallayout. In my Verticallayout, I am using textfields and comboboxes.
Before calling a rest service, I want to validate my textfields and comboboxes according to minLength, maxLength, required etc..., so I use the isInvalid() method to validate my fields.
I dont use any Binder, I only use Verticallayout and fields.

In this scenario, isInvalid() method is not automatically recognise invalid values of my fields. In GWT, GXT etc other scenarios, isValid() or isInvalid() methods does this automatically, and I dont use any Binder for this.

The only thing I want is that, if my field values invalid according to field limitations, the rest service will not be called...

Must I use Binder for field validation?

Not: If I click any of this fields and I focus them, isInvalid() method works as my expectation without Binder, but I can not click all of them every time and so customers cant.

**Comment by denis-anisimov** [comment] 2018-08-07 10:45
>The comment I wrote was wrong. I corrected it as 'CODE ALWAYS COMES TO THIS LINE'.

That's what I expected from the description.
I don't see ANY reason why the field should be invalid.

>In my scenario, I use a Verticallayout. In my Verticallayout, I am using textfields and comboboxes.

Not relevant information.

>Before calling a rest service, I want to validate my textfields and comboboxes according to minLength, maxLength, required etc..., so I use the isInvalid() method to validate my fields.

I already said that `invalid` should be set somehow. 
I don't see any reason why it should be set from your description.

>In this scenario, isInvalid() method is not automatically recognise invalid values of my fields.

I don't see in which way you values become invalid. There is nothing related to that in the description.

> In GWT, GXT etc other scenarios, isValid() or isInvalid() methods does this automatically, and I dont use any Binder for this.

This is a different framework. No need to expect that it works in the same way as others.

>The only thing I want is that, if my field values invalid according to field limitations, the rest service will not be called...

Where is that limitations are defined ?
Ticket description doesn't contain ANY info about that.

>Must I use Binder for field validation?

You MAY use `Binder` for that. I still have no any idea about your usecase since the ticket description is:
- wrong
- doesn't contain any relevant info

I repeat what I've already said:

When you create a ticket it should contain:
- Exact steps to reproduce.
- Current behavior
- Expected behavior

I see only an expected behavior and wrong current behavior.

**Comment by Legioth** [comment] 2018-08-07 10:59
My understanding here is that the issue is that the `valid` property is not automatically synchronized back to the server when the client-side status changes?
