### ISSUE TITLE
Filtering problem using slow DataProvider

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-combo-box-flow#296] opened 2019-09-30 19:04 UTC
### Vaadin Framework version
Tested on Vaadin 14.0.6 and 14.0.7
### Browser version
Chrome Version 77.0.3865.90
### Web container name and version
Jetty 9.4.15.v20190215
### Description of the bug
When using a DataProvider that takes half a second to load the data from backend, it seems to be a race condition when losing and getting focus again, after selecting an item.
### Minimal reproducible example
[See attached project](https://github.com/vaadin/vaadin-combo-box-flow/files/3672807/combobox-problem.zip)
Animated gif showing the problem:
![ComboProblem](https://user-images.githubusercontent.com/28312758/65907727-45ae5600-e39b-11e9-8f48-688f268666ed.gif)
It can be reproduced by doing this with only the keyboard:
1) Focus on the combobox
2) Press "a", wait until the item is shown and then select it by "down" and "enter"
3) Press "tab" to loose focus
4) Press "shift"+"tab" to gain focus again
5) Press "a" again
### Expected behavior
The combobox should show the filtered item
### Actual behavior
The loading indicator remains visible and the filtered item does not appear

**Comment by pekam** [comment] 2019-10-03 07:58
A similar case, which probably has the same underlying cause:
1. Enter a filter, let's say "a", and wait for the data to load
2. Type quickly another key and backspace to get back to filter "a"
3. Notice that data is not loaded and loading indicator remains visible

The server gets requests with the same arguments:
1. start: 0, end: 50, filter: "a"
2. start: 0, end: 50, filter: "a"

The server most likely ignores the second request, because based on the arguments the client should already have all the relevant data. There are two possible approaches for fixing this:
- client: add caching so that it can provide the data immediately if the request would be a duplicate of the previous one (don't make the server-call at all in this case)
- server: force it somehow to resend the data in this scenario

**Closed** 2019-10-21 14:25 UTC
Labels: BFP
