### ISSUE TITLE
After selecting item the `getValue` returns null, when CB has addCustomValueSetListener

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-combo-box-flow#237] opened 2019-03-20 07:45 UTC
**CB version: 2.1.1**

### Description:
After selecting the item from the Combobox by typing the value and pressing Enter, the `getValue()` returns null

### Steps to reproduce: 
```
  ComboBox<Person> cb2 = new ComboBox<>("People");
 ListDataProvider<Person> ldp = new ListDataProvider<>(
                        new PersonRepository().getPersons());
 cb2.setDataProvider(ldp);
 cb2.setItemLabelGenerator(person -> person.getFirstName());  
 cb2.addCustomValueSetListener(ev -> {
                        String v = ev.getDetail();
                        System.out.println(v);
                });

 Button getValue = new Button("Get cb value", e->{
                        //PRINTS NULL
                        System.out.println("Value: "+cb2.getValue());
                });
 add(cb2);
 add(getValue);
```

**Comment by pekam** [comment] 2019-03-20 08:25
The problem is that a custom value is always a `String`, but the `ComboBox` bean type is `Person`. The `ComboBox` doesn't know how to generate a new `Person` object based on the entered `String`.

I'm not 100% sure what is the specification of how the custom value feature should work, but I guess that because of this limitation, you should define in the `CustomValueSetListener` how to create the new `Person` object based on the given custom `String`.

For example, something like this:
```java
comboBox.addCustomValueSetListener(e -> {
    Person newValue = new Person();
    newValue.setFirstName(e.getDetail());
    listDataProvider.getItems().add(newValue);
    listDataProvider.refreshAll();
    comboBox.setValue(newValue);
});
```

**Comment by anasmi** [comment] 2019-03-20 08:29
Thanks for checking, @pekam :)

**Comment by pekam** [comment] 2019-05-14 09:10
I'm closing this issue for the reason stated above.

I've added a demo that showcases how you need to update the value manually: #259 
Also, JavaDocs have been improved to explain how the feature should be used: #255

**Closed by pekam** 2019-05-14 09:10 UTC
Labels: wontfix
