### ISSUE TITLE
Comboboxes that gets data with a data provider that returns 0 objects never closes the fetching indicator

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/vaadin-combo-box-flow#178] opened 2018-12-19 11:22 UTC
If you have a combobox with a data provider that results in 0 items the loading indicator will never dissapear.

I have modified the demo to show this bug in:
https://github.com/brp-benjamin/vaadin-combo-box-flow/tree/combobox-overlay-bugs

See this screenshot of the error
![card-overlay-empty-error-screenshot](https://user-images.githubusercontent.com/42134286/50217379-c8c06b80-0388-11e9-8dd8-7d5afe9310ce.png)

**Comment by pekam** [comment] 2018-12-19 11:32
Interesting. This was already been fixed in the 2.0 beta phase, and there's a test case for it: https://github.com/vaadin/vaadin-combo-box-flow/pull/153
Maybe there's some difference between this use-case and the test-case.

**Comment by denis-anisimov** [comment] 2018-12-19 11:39
Your project contains a huge number of files (because it's the `vaadin-combobox-flow` project)  and I'm not able to identify which file exactly should I use to run and see the behavior.
The simple search didn't help me.

So please don't use such complicated projects for reporting issues.
Please use https://github.com/vaadin/skeleton-starter-flow or just a code snippet which I can copy-paste **_AS IS_** to reproduce the issue.

**Comment by pekam** [comment] 2018-12-19 11:46
@denis-anisimov it's easy to see the few lines that reproduce these bugs by looking at the file diff in the last commit.

**Comment by denis-anisimov** [comment] 2018-12-19 11:52
If you are able to reproduce it then I'm totally OK.

**Comment by pekam** [comment] 2018-12-19 12:36
The fix in https://github.com/vaadin/vaadin-combo-box-flow/pull/153 is applied when the server returns an empty array of data. To be more specific, it happens when the server calls client-side `comboBox.$connector.set(0, [])`.

When the overlay is opened another time, the server doesn't call this function anymore, probably because it knows that the client has made that query already and should have the correct data. Because of this the client-side dataprovider call is never called by invoking its callback function.

**Comment by brp-benjamin** [comment] 2019-02-07 14:45
Any updates on this?

**Comment by pekam** [comment] 2019-02-12 10:24
PR for fixing this in the web component: https://github.com/vaadin/vaadin-combo-box/pull/772

PR for adding a test also to this repository to avoid regressions: https://github.com/vaadin/vaadin-combo-box-flow/pull/206

**Closed** 2019-02-15 13:31 UTC
Labels: bug, in review
