### ISSUE TITLE
Invalid value is set  to Combobox if labelGenerator contains a label for this invalid option

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-combo-box-flow#194] opened 2019-01-24 06:31 UTC
Flow: 12.0.4
Combobox: 2.0.2
Running the example above the value is set to None, but Combobox doesn't have this value. 

```
public enum Gender {
        Male, Female, None;
}

 private void addComboTest() {
            
       ComboBox combo = new ComboBox( "Select Value" );
       combo.setId( "Gender" );
       combo.setPreventInvalidInput( true );
       combo.setAllowCustomValue( false );
        combo.setId( "Gender" );
        add( combo );
     //Here the values for combobox is filtering out 
        Map<Object, String> allItems = new LinkedHashMap<>();
        Map<Object, String> items = new LinkedHashMap<>();
        for( Gender e : Gender.values() ) {
            if( e != Gender.None ) {
                items.put( e, e.name() );
            }
            allItems.put( e, e.name() );
        }
        combo.setItems( items.keySet() );
        combo.setItemLabelGenerator( allItems::get );

        Button ok = new Button( "Select None" );
        ok.addClickListener( event -> {
            combo.setValue( Gender.None );
        } );
        add( ok );
    }
```
Changing to 
```
combo.setItemLabelGenerator( items::get );
```
 fires ```java.lang.IllegalStateException: Got 'null' as a label value for the item 'None'. 'ItemLabelGenerator' instance may not return 'null' values``` is thrown.

**Comment by pekam** [comment] 2019-02-12 12:51
Seems that there are two non-related issues in this description:
1. Combo box allows setting a value which is not contained in the item set.
2. When `itemLabelGenerator` returns `null`, it throws and exception.

Both of these are intentional features.

The first one is a consequence of the lazy loading support. See my explanation in https://github.com/vaadin/vaadin-combo-box-flow/issues/176#issuecomment-448560132, and the follow-up discussion.

The second point is expected as well. The fact that it can be reproduced also with an item which is not contained by the combo box is just a consequence of the first point.

I'm going to close this issue as a duplicate of #176, since the underlying problem (if you see it as a problem) is the same. Let's keep that ticket open for discussion about whether we could prevent non-existing values being set to a combo box.

**Closed by pekam** 2019-02-12 12:51 UTC
